services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ilya_podkin
      POSTGRES_PASSWORD: qwerty4415@
      POSTGRES_DB: BookifyDB
    ports:
      - "8080:8080"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
